spring.application.name=nail-salon-booking
jwt.secret=aVeryLongSecretKeyThatShouldBeAtLeast256BitsLongForHS256Algorithm
jwt.expiration=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/nail_salon_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
